export default {
  db: null,
  adminPassword: 31013,
  updateCompanyId: "",
  updateUserId: "",
  isReadOnlyUpdateUserDetail: false,
  updateDelinquentId: "",
  companyList: [],
  userList: [],
  blackList: [],
  delinquentList: [],
  userSearchType: "입주자명",
  userSearchKeyword: "",
  companySearchType: "会社名",
  companySearchKeyword: "",
  delinquentSearchType: "멘션명",
  delinquentSearchKeyword: "",
  delinquentFilterType: "滞納報告型",
  blackListSearchType: "멘션명",
  blackListSearchKeyword: "",
  tabIndex: 0,
  isUnLogin: true,
  successMessage: "",
  errorMessage: ""
};
