export const T = {
  GET_COMPANY_LIST: "GET_COMPANY_LIST",
  GET_USER_LIST: "GET_USER_LIST",
  SEARCH_COMPANY: "SEARCH_COMPANY",
  SEARCH_USER: "SEARCH_USER",
  CHANGE_TAB_INDEX: "CHANGE_TAB_INDEX",
  CHANGE_UPDATE_COMPNAY_ID: "CHANGE_UPDATE_COMPNAY_ID",
  DELETE_COMPANY: "DELETE_COMPANY",
  GET_USER_LIST: "GET_USER_LIST",
};
